#$ -cwd
#$ -q high_mem
#$ -S /bin/bash
#$ -pe mpich 20

module load SGA/v0.10.15

FILE1=../../../../DATA/A.Antonelli/results/fastq_trimmed/P5201_101_S17_L006_R1_001.fastq
FILE2=../../../../DATA/A.Antonelli/results/fastq_trimmed/P5201_101_S17_L006_R2_001.fastq
PREPROCESSED=C_cal_A.Antonelli_16_04_550bp.preprocessed.fastq
GENOME=C_cal_A.Antonelli_16_04_550bp.preqc

sga preprocess --pe-mode 1 $FILE1 $FILE2 > $PREPROCESSED
sga index -a ropebwt --no-reverse -t $NSLOTS $PREPROCESSED
sga preqc -t $NSLOTS $PREPROCESSED > $GENOME
sga-preqc-report.py $GENOME /usr/local/packages/sga-0.10.15/src/examples/preqc/*.preqc
